In [1]:
numlist=[1,2,3,4,4]
numlist

[1, 2, 3, 4, 4]

In [2]:
abs(-5)

5

In [ ]:
# python has many modules to make features such s sqrt and all


In [3]:
import numpy as np # numpy module imported
np.mean(numlist)

np.float64(2.8)

In [4]:
np.sqrt(4)

np.float64(2.0)

## np.linspace(x,y,z) : creates evenly spaces numbers between x and y . z = amount of numbers to be generated.
## default value of z=50

In [5]:
np.linspace(1,10,7) 

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [6]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## shift+tab pressed inside a function opens a doctstring describing functionality of that function

In [8]:
funout = np.linspace(1,10,12)
funout


array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [9]:
funout+2 # adds 2 to all numbers in funout


array([ 3.        ,  3.81818182,  4.63636364,  5.45454545,  6.27272727,
        7.09090909,  7.90909091,  8.72727273,  9.54545455, 10.36363636,
       11.18181818, 12.        ])

1) create list of 15 numbers fro 4 to 100
2) round those numbers to nearest integers
3) print out #2
4) print out square root of each number in the list


In [11]:
import numpy as np
l=np.linspace(4,100,15)
print(l)

[  4.          10.85714286  17.71428571  24.57142857  31.42857143
  38.28571429  45.14285714  52.          58.85714286  65.71428571
  72.57142857  79.42857143  86.28571429  93.14285714 100.        ]


<list>.astype(x): used to convert np list into a specefic datatype

In [14]:
round_l=np.round(l).astype(int)
round_l

array([  4,  11,  18,  25,  31,  38,  45,  52,  59,  66,  73,  79,  86,
        93, 100])

In [16]:
sq_l= np.sqrt(round_l) # np.sqrt gives square root of all numbers in the list
sq_l

array([ 2.        ,  3.31662479,  4.24264069,  5.        ,  5.56776436,
        6.164414  ,  6.70820393,  7.21110255,  7.68114575,  8.1240384 ,
        8.54400375,  8.88819442,  9.2736185 ,  9.64365076, 10.        ])

## np.arange(x,y) 
creates. list of integers from x to (y-1)

In [2]:
import numpy as np
x=np.arange(-9,10)
print(x)

[-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9]


In [1]:
import numpy as np
import sys 
import time


In [3]:
l=range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [6]:
arr=np.arange(1000)
print(arr.size*arr.itemsize)

8000


In [7]:
print(arr.size) # size of numpy array

1000


In [8]:
print(arr.itemsize) # size of one onject of numpy array

8


In [12]:
size=100000
l1=range(size)
l2=range(size)
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print(" normal time ", (time.time()-start)*1000)

# numpy array


a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result = a1+a2 # directly adds eacj element of numpy array

print(" numpy time ", (time.time()-start)*1000)



  

 normal time  66.50495529174805
 numpy time  3.015756607055664


In [15]:
x=np.array([1,2,3,4])
y=np.array([6,7,8,9])
z1=x+y
print(z1)
z2=x-y
print(z2)
z3=x*y
print(z3)
z4=x/y
print(z4)
z5=x**y
print(z5)


[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]
[     1    128   6561 262144]


In [17]:
a=np.array([5,6,7])
a.ndim

1

In [21]:
a=np.array([[2,3],[4,5]])
a.ndim


2

In [22]:
a.shape

(2, 2)

In [24]:
a=np.array([[2,3],[4,5]],dtype=complex)
a

array([[2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j]])

In [25]:
a=np.array([[2,3],[4,5]],dtype=float)
a

array([[2., 3.],
       [4., 5.]])

In [29]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
a=np.array([[2,3],[4,5],[7,9]])
a
a.shape

(3, 2)

In [40]:
x=a.reshape(2,3)
x


array([[2, 3, 4],
       [5, 7, 9]])

In [41]:
x=a.reshape(6,1)
x

array([[2],
       [3],
       [4],
       [5],
       [7],
       [9]])

In [42]:
x=a.ravel()
x

array([2, 3, 4, 5, 7, 9])

In [46]:
a=np.array([[2,3],[4,5],[7,9]])
s=a.sum()
print(s)

30


In [47]:
a=np.array([[2,3],[4,5],[7,9]])
s=a.sum(axis=0)
print(s)

[13 17]


In [48]:
s=a.sum(axis=1)
s

array([ 5,  9, 16])

In [52]:
st=np.std(a)
print(st)

2.3804761428476167


In [53]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [54]:
print(a.sum(axis=0)) # sum pf columns

[16 12 13]


In [55]:
print(a[1,2])

3


In [57]:
a[0:2,1:3]

array([[7, 8],
       [2, 3]])

In [58]:
a[0:2,1]

array([7, 2])

In [59]:
a[0:2,:] # print first  2 rowa and all coulmns

array([[6, 7, 8],
       [1, 2, 3]])

In [62]:
for x in a.flat:
    print(x)

6
7
8
1
2
3
9
3
2


In [63]:
for r in a:
    print(r)

[6 7 8]
[1 2 3]
[9 3 2]


In [72]:
for r in a:
    print(r[0:2])

[6 7]
[1 2]
[9 3]


In [74]:
a=np.arange(6).reshape(3,2)
a
b=np.arange(6,12).reshape(3,2)
b
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [75]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [76]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [77]:
a.shape

(2, 15)

In [78]:
a1=np.hsplit(a,3)

In [80]:

for c in a1:
    print(c)

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [90]:
a2=np.array_split(a,3,axis=0)
a2

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]),
 array([], shape=(0, 15), dtype=int64)]

In [91]:
# boolean arrays 

a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [94]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [95]:
a[a!=3]

array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
c=a[a%2==0] # extract all even numbers from array a
c

array([ 0,  2,  4,  6,  8, 10])

In [96]:
# iterating from
a=np.arange(12).reshape(3,4)

In [97]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])